
word = ["s","t","e","i","n","w","a","y"]  #The word will be random generated by the program, "steinway" is an example word here.
length = len(word)
blank = []
for x in range(0,length):
    blank.append('___')
print(blank)
killswitch = True
while killswitch == True:
    guess = input("Enter your guess [a letter] : ") # The guess from the player
    guessL = guess.lower() #convert to lower case so it can take captilazied input
    position = -1
    killswitch1 = True
    while killswitch1 == True:
        for x in word:
            position += 1
            if guessL == x:
                print("Congradulations, you found a correct characer! ")
                blank[position] = guessL
                print(blank)
            else:
                print("Try again")    
                killswitch1 = False       
            if blank == word:
                print("congradulations,you beat the game")
                killswitch = False

    
    
        

        
